name: unit-test-self-hosted
# This is a template workflow to be run using Hyke's self-hosted runners
# Copy and paste it into your repository under .github/workflows

# This workflow runs unit tests for packages in workspace
# Requires: pre-built packages repo


# Uncomment triggers below to run it when build-dependencies workflow completes 
on:
  # workflow_run:
  #   workflows: ["build-dependencies-self-hosted"] 
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  unit-test-self-hosted:
    runs-on: self-hosted
    # Uncomment following line run it when build-dependencies workflow completes successfully
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: build-master
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup and Unit test
        env:
            ROS_DISTRO: ${{ vars.ROS_DISTRO }}  
        run: |
          cd /autoware
          source /opt/ros/$ROS_DISTRO/setup.bash
          source install/setup.bash
          colcon test-result --delete-yes  
          colcon test 
          colcon test-result --verbose
